# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool: HC-CDO Self-Hosted

variables:
  tag: '$(Build.BuildId)'
  azureContainerRegistry: ragdockertest.azurecr.io
#   azureSubscriptionEndpoint: HcSx-SP-RAGNalysis-JuniorMegalosaurus 

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/kafka LLM log/consumer-service/Dockerfile'
        tags: |
          $(tagVersion)
          $(tagDate)
    - task: DockerCompose@0
      displayName: Build CI Containers
      inputs:
        action: Run A Docker Compose command
        dockerComposeFile: '$(Build.SourcesDirectory)/kafka LLM log/docker-compose.yml'
        abortOnContainerExit: true
        buildImages: true
        dockerComposeCommand: -f '$(Build.SourcesDirectory)/kafka LLM log/docker-compose.yaml' build