version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-cluster:
    image: wurstmeister/kafka
    depends_on: 
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9092, OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092, OUTSIDE://:9094 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  producer:
     build: ./producer-service
     depends_on:
      - kafka-cluster
     tty: true
     imagePullPolicy: Never 
  consumer:
     build: ./consumer-service 
     depends_on: 
      - kafka-cluster   
     tty: true
     ports:
      - "9090:9090"
     imagePullPolicy: Never
  nlp:
     build: ./nlp-service
     depends_on:
      - kafka-cluster
     tty: true
     ports:
      - "9095:9095"
     imagePullPolicy: Never