apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nlp
  name: nlp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nlp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: nlp
    spec:
      containers:
        - image: kafkasepcontainers-nlp
          name: nlp
          ports:
            - containerPort: 9095
          resources: {}
          tty: true
          imagePullPolicy: Never 
      restartPolicy: Always
status: {}
